### ISSUE TITLE
[CICD] Add github action to auto-update gh-page after tagging

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-ml#208]
After a release tagging https://github.com/NVIDIA/spark-rapids-ml/tags,
create a github action to auto update https://github.com/NVIDIA/spark-rapids-ml/tree/gh-pages based on new tag

triggers could be sth like
```
name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
```
